---
title: "Spatial data science in an age of scientific disruption"
description: Notes on sessions at AAG 2024
author: "David O'Sullivan"
toc: true
categories:
  - geography
  - spatial
date: 04-16-2024
draft: true
---

## Purpose of the sessions
Reflections on UCSB specialist meetings in [_Spatial Data Science in an Age of Scientific Disruption_](https://spatial.ucsb.edu/events/all/2023/spatial-data-science-age-scientific-disruption).

### Angie Lee, Esri
Problem-based learning. AI makes learning about framing questions well and interpreting outcomes.

### Clancy Wilmott, UCB
Going back to the geography&mdash;broader social implications.

Not about 'solving' problems, about helping.

Going behind the data.

Starting with the code (right-click **View page source**).

AI can be about when you already know the question and the answer, but can't be bothered to join the dots between. So brings the focus back to the geographer.

### John Wilson, USC
Outcomes.

Disciplinary and university constraints on how we get where we want to.

Spatial XXX always requires input from XXX so is always about listening.

### Peter Kedron, UCSB
Chair panel 1. Panellist session 2.

In responses mentioned how we don't document the paths not taken _en route_ to the published version of research. Reporting those would make clear that failing is normal (cf. conversations about modeller's notebooks in agent-based modelling).

### Joseph Holler, Middlebury College
Group-based.

FOSS. Github etc.

Emphasis on replication, reproducibility of science.

Datasets are problematic... finally!

Ask good questions. How to ask good questions. This was a theme in the specialist meeting.

### Steve Manson, Minnesota
Wider university perspective of the discipline of geography. 

Spatial data science is inductive, that drapes methods onto problems, too enamoured with blackboxes. We've gone along with that&mdash;solutions/methods that are essentially commercial generic solutions, not properly integrated with existing science. Importance of integrations with domain theories.

There is a wider crisis in science (publishing, data, methods).

Local really matters. Working with local groups is important.

One of the few successes from outside academia is local government interventions. Natural experiment in efficacy of school lunches. Only the existence of spatial infrastructure that enabled that.

### Bo Zhao, Washington
[Humanistic GIS](http://dx.doi.org/10.1080/24694452.2021.2004875), [deep fake geographies](https://doi.org/10.1080/15230406.2021.1910075).

History of giscience is a history of disruptions.

Linking with digital geographies... (_plus ça change_), e.g. Friday Harbor.

### Mike Goodchild
'Bifurcation': using GIS to advance science _vs_ there is a science of GIS. What we are seeing today is another bifurcation: traditional objectives of research, discovery, patterns, 'truths', EDU (exploration, discovery, understanding). On the other hand a lot of published giscience today is not about discovery, it's about how to tackle a problem, not about advancing understanding. The infrastructure questions (the latter) are legitimate problems.

We have gravitated back toward 'spatial data handling' (Tomlinson).

Where have ideas come from outside academia that have 'worked'? Digital twins, yada yada yada.

### Amy Frazier, UCSB
Chair panel 2.

## From the floor
#### Peter Rogerson, SUNY
Fear of failure. General assent to the importance of this in teaching.

#### Michael Widener, Toronto
Can spatial data science bring geography together? Should it be about this? JW spoke at length about spatial institute at USC. JH spoke to small core geography.

#### Harvey Miller, OSU
(S1) How can giscience contribute in an era of disruption? 

Harvey's question in S1  an interesting one... it got me thinking about the difficulty of geography being integrative _vs_ the move to $(x,y,z[,t])$ that spatial data science tends to push us towards.

(S2) Data rich now, not data poor, how does that enable closing the loop on exploration, intervention, in understanding complex systems.

#### Eric Shook (Minnesota)
Accused panel of pessimism/cynicism.

#### Rachel Franklin, Newcastle
What's with all the _men_? More importantly: why do we keep talking about methods-oriented framings (GIScience, Spatial Data Science) rather than _quantitative geography_?

#### David O'Sullivan, no fixed abode
I have this book...
