project:
  type: website
  output-dir: docs

website:
  title: "Geospatial Stuff"
  navbar:
    logo: /images/gs-logo.png
    right:
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Posts"
        file: blog.qmd
      - text: "Training"
        file: training.qmd
      - text: "Academic"
        menu:
          - text: "Books"
            file: books.qmd
          - text: "Presentations"
            file: presentations.qmd
          - text: "Publications"
            file: publications.qmd
      # - text: "About"
      #   file: index.qmd
      - icon: github
        href: https://github.com/DOSull
  favicon: /images/gs-logo.png
  body-footer: |
    <p class="page-footer"><a href="/" class="unboxed-link"><img src="/images/gs-logo.png" style="height:36px; vertical-align:-11px; padding-right:1px;">Geospatial Stuff</a></p>
    

format:
  html:
    theme: lux
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:\/\/|https:\/\/)(?:dosull\.github\.io|dosull|southosullivan\.com|github\.com\/DOSull|southosullivan\.com|github\.com\/DOSull|patternandprocess\.org|computinggeographically\.org)'

