project:
  type: website
  output-dir: docs

website:
  title: Geospatial <br>Stuff
  navbar:
    logo: /images/gs-logo-corrected.png
    right:
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Posts"
        file: blog.qmd
      - text: "Training"
        file: training.qmd
      - text: "More"
        menu:
          - text: "Books"
            file: books.qmd
          - text: "Presentations"
            file: presentations.qmd
          - text: "Publication list"
            file: publications.qmd
          - text: |
              Computing Geographically![](/images/box-arrow-up-right.svg)
            href: https://dosull.github.io/computing-geographically
            target: _blank
          - text: |
              Spatial Simulation![](/images/box-arrow-up-right.svg)
            href: https://dosull.github.io/pattern-and-process
            target: _blank
          - text: |
              30 Day Map Challenge 2023![](/images/box-arrow-up-right.svg)
            href: https://dosull.github.io/30-day-maps-2023
            target: _blank
      - icon: github
        href: https://github.com/DOSull
      - icon: linkedin
        href: https://www.linkedin.com/in/david-o-sullivan-1b8a901b7/
  favicon: /images/gs-logo-corrected.png
  body-footer: |
    <a href="/"><img src="/images/gs-logo-corrected.png" style="height:36px;" alt="Geospatial Stuff"></a>
    

format:
  html:
    theme: lux
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:\/\/|https:\/\/)(?:dosull\.github\.io|dosull|southosullivan\.com|github\.com\/DOSull|southosullivan\.com|github\.com\/DOSull|patternandprocess\.org|computinggeographically\.org)'
    highlight-style: ayu