project:
  type: website
  output-dir: docs

website:
  title: "Geospatial Stuff"
  navbar:
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "Training"
        file: training.qmd
      - text: "Academic"
        menu:
          - text: "Books"
            file: books.qmd
          - text: "Presentations"
            file: presentations.qmd
          - text: "Publications"
            file: publications.qmd
      - text: "Other stuff"
        file: other.qmd
      - icon: github
        href: https://github.com/DOSull
format:
  html:
    theme: lux
    css: styles.css



