project:
  type: website
  output-dir: docs

website:
  title: Geospatial <br>Stuff
  navbar:
    logo: /images/gs-logo-corrected.png
    right:
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Posts"
        file: blog.qmd
      - text: "Training"
        file: training.qmd
      - text: "Academic"
        menu:
          - text: "Books"
            file: books.qmd
          - text: "Presentations"
            file: presentations.qmd
          - text: "Publications"
            file: publications.qmd
      # - text: "About"
      #   file: index.qmd
      - icon: github
        href: https://github.com/DOSull
      - icon: linkedin
        href: https://www.linkedin.com/in/david-o-sullivan-1b8a901b7/
  favicon: /images/gs-logo-corrected.png
  body-footer: |
    <a href="/"><img src="/images/gs-logo-corrected.png" style="height:36px;" alt="Geospatial Stuff"></a>
    

format:
  html:
    theme: lux
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:\/\/|https:\/\/)(?:dosull\.github\.io|dosull|southosullivan\.com|github\.com\/DOSull|southosullivan\.com|github\.com\/DOSull|patternandprocess\.org|computinggeographically\.org)'

