---
title: "Presentations"
description: "These are in reverse chronological order" 
title-block-banner: true
---

Most talks are in web formats, and may include links that are now broken. Others are PDFs. Others are missing, but are listed because they give a sense of development over time.



Date | Title | Notes
:-- | :-- | :--
2025<br>September | Modelling potential environmental impacts of science activity in Antarctica ([dark](https://dosull.github.io/antarctica/talk/)&#124;[light](https://dosull.github.io/antarctica/talk/index-2.html)) theme | Regional GIS Forum, Palmerston North, 26 September.
2025<br>July | [The latest on tiled multivariate maps](https://dosull.github.io/weaving-space/presentations/NZCS-Jul-2025/) | New Zealand Cartographic Society, Te Herenga Waka, 4 July.
2025<br>June | [It's turtles all the way down: Simple models - complex outcomes](https://southosullivan.com/talks/cafe-complexite-2025/) | Café Complexité, Te Herenga Waka, 5 June.
2025<br>May | [Look ma! (Almost) no javascript!](https://dosull.github.io/weaving-space/presentations/Wellington-Python-meetup-2025/) | Python NZ Wellington Meetup, Sharesies Offices, Wellington, 15 May. [Video](https://www.youtube.com/watch?v=4okZcHhQQgg)
2024<br>August | [Time-space mapping in mountainous terrain](https://southosullivan.com/talks/GeoCart-2024/) | GeoCart 2024, National Library, Wellington, 21-23 August
2024<br>April | [A spatially explicit agent-based model of on-farm environmental interventions](https://southosullivan.com/talks/AAG-2024/) | Annual Meeting of the American Association of Geographers, Honolulu, Hawai'i, United States
2024<br>March | [30 Day Map Challenge 2023](https://dosull.github.io/30-day-maps-2023/maps/maptime/maptime-30-days.html) | Maptime! Wellington
2023<br>September | [From geographical information science via spatial data science to geographical computing](https://southosullivan.com/talks/SDSS-2023-UCanterbury/) | Fourth Spatial Data Science Symposium, University of Canterbury Hub, 7 September
2023<br>August | [Computing Geographically: Bridging Giscience and Geography](https://southosullivan.com/talks/UCanterbury-seminar-2023/) | University of Canterbury, School of Earth and Environment, Research Seminar, 10 August
2022<br>November | [Tiled & woven thematic maps](https://dosull.github.io/weaving-space/presentations/Palmerston-North-Nov-2022/slides/) | Regional GIS Forum, Palmerston North, 11 November
2022<br>August | [Computing geographically: rethinking space and place in giscience](https://southosullivan.com/talks/NZGRC-2022/#/) | Keynote at New Zealand Geospatial Research Colloquium, 29-30 August
2022<br>August | [Tiled & woven thematic maps](https://dosull.github.io/weaving-space/presentations/NZCS-Aug-2022/slides/) | GeoCart 2022, National Library, Wellington, 24-26 August
2022<br>July | [R for geospatial](https://southosullivan.com/talks/slug-talk/) | Spatial Literacy User Group, Te Herenga Waka - Victoria University of Wellington
2021<br>November | [Weaving maps of multivariate data](https://dosull.github.io/weaving-space/presentations/NZCS-Nov-2021/make-weave-map.html) | [State of New Zealand Cartography](https://cartography.org.nz/events/geospatial2021), Special Meeting of the New Zealand Cartographic Society, Wellington
2021<br>September | [Mapping the Dulux Colours of New Zealand Using R](dulux-colours-map/slides/) | Maptime! Aotearoa, online
2020<br>November | [Spatially-explicit models for exploring COVID-19 lockdown strategies](https://southosullivan.com/talks/NZGS-2020-covid-model/) | New Zealand Geographical Society, Wellington
2020<br>November | [Computing geographically: rethinking giscience as geography](https://southosullivan.com/talks/Utah-GAW-2020/) | University of Utah, Department of Geography, Geography Awareness Week Colloquium
2019<br>September | [A spatial simulation model to explore the potential impact of gene drives as a control on invasive wasps](https://southosullivan.com/talks/geomputation-2019/) | Geocomputation 2019, Queenstown, 18-21 September
2019<br>August | [Theoretical geography: definitely harder than physics!](https://southosullivan.com/talks/theoretical-geography/) | VvoIP_Physics_Debates symposium
2019<br>July | [Avoiding the YAAWN syndrome](https://southosullivan.com/talks/ABM-for-theory-Hanover-2019/) | Agents for Theory: From Cases to General Principles, Theory Development through Agent-based Modeling, International Workshop held at Herrenhäuser Palace, Hanover, Germany
2018<br>May | [Some translation required, or: A city is not a network either!](https://southosullivan.com/talks/UWTacoma-May-2018/) | Inaugural Brian Coffey lecture and workshop in Geographical Information Science University of Washington, Tacoma
2018<br>April | Computing with many spaces: Generalizing projections for the digital geohumanities and GIScience | (with Luke Bergmann who presented) 114th Annual Meeting of the American Association of Geographers, New Orleans, LA
2018<br>March | [Reimagining GIScience for relational spaces](https://southosullivan.com/talks/UCBoulder-March-2018/) | University of Colorado Boulder, Department of Geography Colloquium Series
2017<br>December | [Bridging GIScience and Geographical Thought](https://southosullivan.com/talks/Liverpool-2017/) | Geographic Data Science Lab, University of Liverpool
2017<br>September | [Identifying ‘narrative arcs’ to explain outcomes in an agent-based model of island resource exploitation](https://southosullivan.com/talks/stanford-panel/) | Graduate webinar series on Agent-based models, University of Minnesota. These are the same slides as a talk at Stanford a couple of years earlier...
2017<br>September | [Some translation required, or: A city is not a network either!](https://southosullivan.com/talks/UrbanNetworksSymposium/) | International Symposium on The Future of Urban Network Research, University of Ghent, Belgium
2017<br>April | ‘Same only different’: rethinking the practice of digital urban geographies | 113th Meeting of the American Association of Geographers, Boston, MA
2016<br>November | [Simple spatial models: Building blocks for a process-based GIS?](https://southosullivan.com/talks/GIF-Nov2016/) | Geolunch Series, Geospatial Innovation Facility (GIF), University of California, Berkeley
2016<br>September | [Searching for common ground (again)](https://southosullivan.com/talks/GIScience2016-presentation/) | (with Jim Thatcher and Luke Bergmann) Presented at 9th International Conference on Geographical Information Science (GIScience 2016), Montreal, Canada
2016<br>September | [Simple simulation models as a complexity ‘pattern language’](https://southosullivan.com/talks/GIScience-lightningTalk/) | Lightning talk at Rethinking the ABCs: Agent-Based Models and Complexity Science in the age of Big Data, CyberGIS, and Sensor Networks pre-conference workshop at GIScience 2016, Montreal, Canada
2016<br>March | [Spatiality, maps, mathematics and critical human geography](https://southosullivan.com/talks/Uppsala-SpatialityMapsMath/) | University of Uppsala, Department of Social and Economic Geography
2016<br>January | [Future GIS](https://southosullivan.com/talks/UBC-Future-GIS/) | (with Matt Wilson) University of British Columbia, Department of Geography
2015<br>December | [Thinking with and about models in geography](https://southosullivan.com/talks/UCDavis-Geography/) | University of California, Davis. Geography Graduate Group seminar series.
2015<br>August | (with Alex Singleton and Seth Spielman) [Our town: How socioeconomics shape functional neighborhoods in American cities](https://southosullivan.com/talks/Geocomputation2015/) | Geocomputation 2015, UT Dallas
2015<br>May | [Spatial simulation: Exploring pattern and process](https://southosullivan.com/talks/UNIGIS/) | UNIGIS Salzburg Webinar
2015<br>May | [Simple spatial models: Building blocks for process-based GIS?](https://southosullivan.com/talks/stanford-lecture/) | Stanford University
2015<br>May | [Identifying ‘narrative arcs’ to explain outcomes in an agent-based model of island resource exploitation](https://southosullivan.com/talks/stanford-panel/) | Stanford University Libraries’ Center for Interdisciplinary Digital Research
2015<br>April | [Identifying ‘narrative arcs’ to explain outcomes in an agent-based model of island resource exploitation](https://southosullivan.com/talks/AAG2015/) | (with George Perry) presented at the 110th Annual Meeting of the Association of American Geographers, Chicago, IL
2014<br>November | [‘Play well’: Learning about the world using spatial models](https://southosullivan.com/talks/Oregon-complexity/) | University of Oregon, Department of Geography and Complexity Science conference
2014<br>September | [Using Personal Names to Explore Cultural, Ethnic and Linguistic Structure in Populations](https://southosullivan.com/talks/DemographyTalk_OSullivan_092414.pdf) | UC Berkeley, Department of Demography
2014<br>June | [Simple spatial models: building blocks for process-based GIS?](https://southosullivan.com/talks/IAG-NZGS-Melbourne-2014.pdf) | Institute of Australian Geographers – New Zealand Geographical Society Joint Conference, University of Melbourne
2013<br>August | [Towards a ‘pattern language’ for spatial simulation models](https://southosullivan.com/talks/SIRC-talk/) | (with George Perry) presented at SIRC NZ 2013, University of Otago, Dunedin, New Zealand. Extended abstract [available here](http://otago.ourarchive.ac.nz/handle/10523/4219)
2013<br>April | [Towards a ‘pattern language’ for spatial simulation models](https://southosullivan.com/talks/AAG2013_talk.pdf) | (with George Perry) presented at the 109th Annual Meeting of the Association of American Geographers, Los Angeles, CA
2013<br>February | [Towards a ‘pattern language’ for spatial simulation models](https://southosullivan.com/talks/UC_SantaBarbara_jobTalk.pdf) | Department of Geography, University of California Santa Barbara
2012<br>May | Naming networks and population structure | Department of Urban Engineering, University of Tokyo
2012<br>May | [Spatial Simulation: Exploring Pattern and Process – A Work in progress](https://southosullivan.com/talks/book_talk_tokyo_2012.pdf) | Centre for Spatial Information Science, University of Tokyo
2012<br>February | [Agent-based models: what are they good for? Or: did Schelling really need an ABM?](https://southosullivan.com/talks/OSullivan_AAG_2012.pdf) | Presented at the 108th Annual Meeting of the Association of American Geographers, New York, NY
2011<br>September | Model Histories: The Generative Properties of Agent-Based Modelling | Presented by James Millington (also with George Perry) at Annual Conference of the Royal Geographical Society with the Institute of British Geographers, Royal Geographical Society, London
2011<br>April | [Naming networks and population structure](https://southosullivan.com/talks/aag2001_osullivanMateos_namingNetworks.pdf) | (with Pablo Mateos) presented at the 107th Annual Meeting of the Association of American Geographers, Seattle, WA
2011<br>April | Do physicists have geography envy? | with Steve Manson (who presented) at the 107th Annual Meeting of the Association of American Geographers, Seattle, WA. This paper was [eventually published in much different form](https://dx.doi.org/10.1080/00045608.2015.1039105) in the *Annals of the American Association of Geographers*.
2009<br>December | [Simulating long distance dispersal processes in spatially heterogeneous landscapes](https://southosullivan.com/talks/geocomp09_osullivanPerry.pdf) | (with George Perry) presented at Geocomputation 2009, University of New South Wales, Sydney, Australia. A [version of this work was published](http://dx.doi.org/10.1016/j.ecoinf.2009.03.001) in *Ecological Informatics*.
