---
title: "Publications"
description: "I try to keep this as up to date as possible..."
---

A similar list is available at my [ORCiD profile](https://orcid.org/0000-0001-8078-3241). You can also see them in citational context at [my google scholar page](https://scholar.google.com/citations?user=6guUlvgAAAAJ&hl=en&oi=ao), which is reasonably accurate.  Links below are generally to official publisher sources, and are often closed, but if you would like a copy, just [email me](mailto:david.osullivan@vuw.ac.nz).

Jump to [books](#books), [papers](#in-refereed-journals), [book chapters](#book-chapters), [dissertations](#dissertations)

## books
**O’Sullivan D**. 2017. Section Editor for ‘Fundamentals of GIScience’ (32 articles) in *The International Encyclopedia of Geography: People, the Earth, Environment, and Technology*. Richardson, D. (ed). New York: Wiley.

Miller JA, **D O’Sullivan** and Wiegand N eds. 2016. *Geographic Information Science: Proceedings of the 9th International Conference, GIScience 2016 Lecture Notes in Computer Science Vol. 9927* (Springer: Cham, Switzerland).

**O’Sullivan D** and GLW Perry. 2013. *Spatial Simulation: Exploring Pattern and Process* (Wiley: Chichester, UK).

**O’Sullivan D** and DJ Unwin. 2010. *Geographic Information Analysis* 2nd edn. (Wiley: Hoboken, NJ).

**O’Sullivan D** and DJ Unwin. 2003. *Geographic Information Analysis* (Wiley: Hoboken, NJ).

## in refereed journals
Etherington T, F Morgan, **D O’Sullivan**. 2022, Binary Space Partitioning Generates Hierarchical and Rectilinear Neutral Landscape Models Suitable for Human-Dominated Landscapes, In review *Landscape Ecology* doi: [10.21203/rs.3.rs-1251602/v1](https://dx.doi.org/10.21203/rs.3.rs-1251602/v1)

Chaves LF, MD Friberg, LA Hurtado, RM Rodríguez, **D O’Sullivan** and LR Bergmann. 2022. Trade, uneven development and people in motion: Used territories and the initial spread of COVID-19 in Mesoamerica and the Caribbean. *Socio-Economic Planning Sciences* **80** (March) 101161. doi: [10.1016/j.seps.2021.101161](https://dx.doi.org/10.1016/j.seps.2021.101161)

Gibadullina A, LR Bergmann and **D O’Sullivan**. 2021. For Geographical Network Analysis. *Tijdschrift voor Economische en Sociale Geografie* **112**(4) 482-487. doi: [10.1111/tesg.12489](https://dx.doi.org/10.1111/tesg.12489).

**O’Sullivan D**. 2021. New mappings of GIScience and geography. A commentary on May Yuan’s ‘GIS research to address tensions in geography.’ *Singapore Journal of Tropical Geography* **42**(1) 31–35. doi: [10.1111/sjtg.12345](https://dx.doi.org/10.1111/sjtg.12345)

**O’Sullivan D**. 2021. Things are how they are because of how they got that way: Thoughts from the beach, on 50 years of Geographical Analysis. *Geographical Analysis* **53**(1) 157–163. doi: [10.1111/gean.12225](https://dx.doi.org/10.1111/gean.12225)

Franklin, RS, V Houlden, C Robinson, D Arribas-Bel, EC Delmelle, U Demšar, HJ Miller, and **D O’Sullivan**. 2021. Who counts? Gender, gatekeeping, and quantitative human geography. *The Professional Geographer* **73**(1) 48–61. doi: [10.1080/00330124.2020.1828944](https://dx.doi.org/10.1080/00330124.2020.1828944)

**O’Sullivan D**, M Gahegan, DJ Exeter and B Adams. 2020. Spatially explicit models for exploring COVID 19 lockdown strategies. *Transactions in GIS* **24**(4) 967–1000. doi: [10.1111/tgis.12660](https://dx.doi.org/10.1111/tgis.12660)

Payne WB and **D O’Sullivan**. 2020. Exploding the phone book: Spatial data arbitrage in the 1990s Internet boom. *Annals of the American Association of Geographers* **110**(2) 391–398. doi: [10.1080/24694452.2019.1656999](https://dx.doi.org/10.1080/24694452.2019.1656999)

Manson S, L An, KC Clarke, A Heppenstall, J Koch, B Krzyzanowski, F Morgan, **D O’Sullivan**, BC Runck, E Shook and L Tesfatsion. 2020. Methodological Issues of Spatial Agent-Based Models. *Journal of Artificial Societies and Social Simulation* 23(1) 3. doi: [10.18564/jasss.4174](https://dx.doi.org/10.18564/jasss.4174)

Christophers B and **D O’Sullivan**. 2019. Intersections of inequality in homeownership in Sweden. Housing Studies **34**(6) 897-924. doi: [10.1080/02673037.2018.1495695](https://dx.doi.org/10.1080/02673037.2018.1495695)

Mavoa S, N Bagheri, MJ Koohsari, AT Kaczynski, KE Lamb, K Oka, **D O’Sullivan** and K Witten. 2019. How do neighbourhood definitions influence the associations between built environment and physical activity? *International Journal of Environmentalal Research and Public Health* **16**. doi: [10.3390/ijerph16091501](https://dx.doi.org/10.3390/ijerph16091501)

**O’Sullivan, D** 2019. Untangling knots: Thoughts on Wilson’s _New Lines_. *Transactions in GIS* **32**(1) 168-169. doi: [10.1111/tgis.12502](http://dx.doi.org/10.1111/tgis.12502)

Liu C, **D O’Sullivan** and GLW Perry. 2018. The rent gap revisited: gentrification in Point Chevalier, Auckland. *Urban Geography* **39**(9) 1300-1325. doi: [10.1080/02723638.2018.1446883](http://dx.doi.org/10.1080/02723638.2018.1446883)

Perry GLW and **D O’Sullivan**. 2018. Identifying narrative descriptions in agent-based models representing past human-environment interactions. *Journal of Archaeological Method and Theory*, **25**(3) 795-813. doi: [10.1007/s10816-017-9355-x](http://dx.doi.org/10.1007/s10816-017-9355-x)

Mavoa S, K Lamb, **D O’Sullivan**, K Witten and M. Smith. 2018. Are disadvantaged children more likely to be excluded from analysis when applying global positioning systems inclusion criteria? *BMC Research Notes*, **11** 578. doi: [10.1186/s13104-018-3681-2](http://dx.doi.org/10.1186/s13104-018-3681-2)

Mahdavi Ardestani B, **D O’Sullivan**, and P Davis. 2018. A multi-scaled agent-based model of residential segregation applied to a real metropolitan area. *Computers, Environment and Urban Systems*, **69** 1-16. doi: [10.1016/j.compenvurbsys.2017.11.002](http://dx.doi.org/10.1016/j.compenvurbsys.2017.11.002)

Bergmann LR and **D O’Sullivan**. 2018. Reimagining GIScience for relational spaces. *The Canadian Geographer / Le Géographe canadien.* **62**(1) 7-14. doi: [10.1111/cag.12405](http://dx.doi.org/10.1111/cag.12405)

Getz WM, CR Marshall, CJ Carlson, L Giuggioli, SJ Ryan, SS Romañach, C Boettiger, SD Chamberlain, L Larsen, P D’Odorico, **D O’Sullivan**. 2018. Making ecological models adequate. *Ecology Letters* **21**(2) 153-166. doi: [10.1111/ele.12893](http://dx.doi.org/10.1111/ele.12893)

**O’Sullivan D**, LR Bergmann, and JE Thatcher. 2018. Spatiality, maps, and mathematics in critical human geography: toward a repetition with difference. *The Professional Geographer* **70**(1) 129-139. doi: [10.1080/00330124.2017.1326081](http://dx.doi.org/10.1080/00330124.2017.1326081)

Harris R, **D O’Sullivan**, M Gahegan, M Charlton, L Comber, P Longley, C Brunsdon, N Malleson, A Heppenstall, A Singleton, D Arribas-Bel, and A Evans. 2017. More bark than bytes? Reflections on 21+ years of geocomputation. *Environment and Planning B: Urban Analytics and City Science* **44**(4) 598-617. doi: [10.1177/2399808317710132.](http://dx.doi.org/10.1177/2399808317710132.)

Liu C and **O’Sullivan**, D. 2016. An abstract model of gentrification as a spatially contagious succession process. *Computers, Environment and Urban Systems* **59** 1-10. doi: [10.1016/j.compenvurbsys.2016.04.004](http://dx.doi.org/10.1016/j.compenvurbsys.2016.04.004)

Thatcher JE, **D O’Sullivan** and D Mahmoudi. 2016. Data colonialism through accumulation by dispossession: new metaphors for everyday data. *Environment and Planning D: Society and Space* **34**(6) 990-1006. doi: [10.1177/0263775816633195](http://dx.doi.org/10.1177/0263775816633195)

Cheung AK-L, G Brierley, and **D O’Sullivan**. 2016. Landscape structure and dynamics on the Qinghai-Tibetan Plateau. *Ecological Modelling* **339** 7-22. doi: [10.1016/j.ecolmodel.2016.07.015](http://dx.doi.org/10.1016/j.ecolmodel.2016.07.015)

Thatcher JE, LR Bergmann, B Ricker, R Rose-Redwood, **D O’Sullivan**, TJ Barnes, LR Barnesmoore, L Beltz Imaoka, R Burns, J Cinnamon, CM Dalton, C Davis, S Dunn, F Harvey, J-K Jung, E Kersten, L Knigge, N Lally, W Lin, D Mahmoudi, M Martin, W Payne, A Sheikh, T Shelton, E Sheppard, CW Strother, A Tarr, MW Wilson, and JC Young. 2016. Revisiting critical GIS. *Environment and Planning A* **48**(5) 815-824. doi: [10.1177/0308518X15622208](http://dx.doi.org/10.1177/0308518X15622208)

**O’Sullivan D**, T Evans, SM Manson, S Metcalf, A Ligmann-Zielinska, and C Bone. 2016. Strategic directions for agent-based modeling: avoiding the YAAWN syndrome. *Journal of Land Use Science* **11**(2) 177-187. doi: [10.1080/1747423X.2015.1030463](http://dx.doi.org/10.1080/1747423X.2015.1030463)

**O’Sullivan D** and SM Manson. 2015. Do physicists have geography envy? And what can geographers learn from it? *Annals of the Association of American Geographers* **105**(4) 704–722. doi: [10.1080/00045608.2015.1039105](http://dx.doi.org/10.1080/00045608.2015.1039105)

Cheung AK-L, **D O’Sullivan** and G Brierley. 2015. Graph-assisted landscape monitoring. *International Journal of Geographical Information Science* **29**(4) 580-605. doi: [10.1080/13658816.2014.989856](http://dx.doi.org/10.1080/13658816.2014.989856)

Etherington TR, EP Holland, and **D O’Sullivan**. 2015. NLMpy: a python software package for the creation of neutral landscape models within a general numerical framework. *Methods in Ecology and Evolution* **6**(2) 164-168. doi: [10.1111/2041-210X.12308](http://dx.doi.org/10.1111/2041-210X.12308)

Hong S-Y, **D O’Sullivan** and Y Sadahiro. 2014. Implementing Spatial Segregation Measures in R. *PLoS ONE* **9**(11): e113767. doi: [10.1371/journal.pone.0113767](http://dx.doi.org/10.1371/journal.pone.0113767)

**O’Sullivan D**. 2014. Don’t panic! The need for change and for curricular pluralism. *Dialogues in Human Geography* **4**(1) 39-44. doi: [10.1177/2043820614525712](http://dx.doi.org/10.1177/2043820614525712)

Millington JDA, **D O’Sullivan** and GLW Perry. 2012. Model histories: Narrative explanation in generative simulation modelling. *Geoforum* **43**(6) 1025-1034. doi: [10.1016/j.geoforum.2012.06.017](http://dx.doi.org/10.1016/j.geoforum.2012.06.017)

Mueller S, DJ Exeter, H Petousis-Harris, N Turner, **D O’Sullivan** and CD Buck. 2012. Measuring disparities in immunisation coverage among children in New Zealand. *Health and Place* **18**(6) 1217-1223. doi: [10.1016/j.healthplace.2012.08.003](http://dx.doi.org/10.1016/j.healthplace.2012.08.003)

Hong S-Y and **D O’Sullivan**. 2012. Detecting ethnic residential clusters using an optimisation clustering method. *International Journal of Geographical Information Science* **26**(8) 1257-1277. doi: [10.1080/13658816.2011.637045](http://10.1080/13658816.2011.637045)

Xue J, W Friesen and **D O’Sullivan**. 2012. Diversity in Chinese Auckland: Hypothesising multiple ethnoburbs. *Population, Space and Place* **18** 579-595. doi: [10.1002/psp.688](http://dx.doi.org/10.1002/psp.688)

Mavoa S, K Witten, T McCreanor, and **D O’Sullivan**. 2012. GIS based destination accessibility via public transit and walking in Auckland, New Zealand. *Journal of Transport Geography* **20**(1) 15-22. doi: [10.1016/j.jtrangeo.2011.10.001](http://dx.doi.org/10.1016/j.jtrangeo.2011.10.001)

Mateos P, PA Longley, and **D O’Sullivan**. 2011. Ethnicity and Population Structure in Personal Naming Networks. *PLoS ONE* **6**(9) e22943. doi: [10.1371/journal.pone.0022943](http://dx.doi.org/10.1371/journal.pone.0022943)

Pearson J, R Lay-Yee, P Davis, **D O’Sullivan**, M von Randow, N Kerse and S Pradhan. 2011. Primary care in an aging society: Building and testing a microsimulation model for policy purposes. *Social Science Computer Review* **29**(1) 21-36. doi: [10.1177/0894439310370087](http://dx.doi.org/10.1177/0894439310370087)

**O’Sullivan D**. 2009. What’s critical about critical GIS? *Cartographica* **44**(1) 7-8. doi: [10.3138/carto.44.1.5](http://dx.doi.org/10.3138/carto.44.1.5)

**O’Sullivan D** and G. L. W. Perry. 2009. A discrete space model for continuous space dispersal processes. *Ecological Informatics* **4**(2) 57-68. doi: [10.1016/j.ecoinf.2009.03.001](http://dx.doi.org/10.1016/j.ecoinf.2009.03.001)

**O’Sullivan D**. 2009. Changing neighborhoods – neighborhoods changing: a framework for spatially explicit agent-based models of social systems. *Sociological Methods and Research* **37**(4) 498-530. doi: [10.1177/0049124109334793](http://dx.doi.org/10.1177/0049124109334793)

Reardon SF, CR Farrell, SA Matthews, **D O’Sullivan**, K Bischoff and G Firebaugh. 2009. Race and space in the 1990s: changes in the geographic scale of racial residential segregation, 1990-2000. *Social Science Research* **38** 55-70. doi: [10.1016/j.ssresearch.2008.10.002](http://dx.doi.org/10.1016/j.ssresearch.2008.10.002)

Lee BA, SF Reardon, G Firebaugh, CR Farrell, SA Matthews and **D O’Sullivan**. 2008. Beyond the census tract: patterns and determinants of racial segregation at multiple geographic scales. *American Sociological Review* **73**(October) 766-791. doi: [10.1177/000312240807300504 ](http://dx.doi.org/10.1177/000312240807300504 )

Reardon SF, SA Matthews, **D O’Sullivan**, BA Lee, G Firebaugh, CR Farrell and K Bischoff. 2008. The geographic scale of metropolitan segregation. *Demography,* **45**(3) 489-514. doi: [10.1353/dem.0.0019](http://dx.doi.org/10.1353/dem.0.0019)

**O’Sullivan D**. 2008. Geographical information science: agent-based models. *Progress in Human Geography* **32**(2) 541-550. doi: [10.1177/0309132507086879](http://dx.doi.org/10.1177/0309132507086879)

**O’Sullivan D** and DWS Wong. 2007. A surface-based approach to measuring spatial segregation. *Geographical Analysis* **39**(2) 147-168. doi: [10.1111/j.1538-4632.2007.00699.x](http://dx.doi.org/10.1111/j.1538-4632.2007.00699.x)

**O’Sullivan D**. 2006. Geographical information science: critical GIS. *Progress in Human Geography* **30**(6) 783-791. doi: [10.1177/0309132506071528](http://dx.doi.org/10.1177/0309132506071528)

Rygel L, **D O’Sullivan** and B Yarnal. 2006. A method for constructing a social vulnerability index: an application to hurricane storm surges in a developed country. *Mitigation and Adaptation Strategies for Global Change* **11**(3) 741-764. doi: [10.1007/s11027-006-0265-6](http://dx.doi.org/10.1007/s11027-006-0265-6)

Manson SM and **D O’Sullivan**. 2006. Complexity theory in the study of space and place. *Environment and Planning A* **38**(4) 677-692. doi: [10.1068/a37100](http://dx.doi.org/10.1068/a37100)

**O’Sullivan D**, JP Messina, SM Manson and TW Crawford. 2006. Space, place, and complexity science. *Environment and Planning A* **38**(4) 611-617. doi: [10.1068/a3812](http://dx.doi.org/10.1068/a3812)

**O’Sullivan D**. 2005. Geographical information science: time changes everything. *Progress in Human Geography* **29**(6) 749-756. doi: [10.1191/0309132505ph581pr](http://dx.doi.org/10.1191/0309132505ph581pr)

Crawford TW, JP Messina, SM Manson and **D O’Sullivan**. 2005. Complexity science, complex systems, and land-use research. *Environment and Planning B: Planning & Design* **32**(5) 792-798. doi: [10.1068/b3206ed](http://dx.doi.org/10.1068/b3206ed)

Reardon SF and **D O’Sullivan**. 2004. Measures of Spatial Segregation. *Sociological Methodology* **34**(1) 121-162. doi: [10.1111/j.0081-1750.2004.00150.x](http://dx.doi.org/10.1111/j.0081-1750.2004.00150.x)

**O’Sullivan D**. 2004. Complexity science and human geography. *Transactions of the Institute of British Geographers* **29**(3) 282-295. doi: [10.1111/j.0020-2754.2004.00321.x](http://dx.doi.org/10.1111/j.0020-2754.2004.00321.x)

**O’Sullivan D**. 2002. Toward micro-scale spatial modelling of gentrification. *Journal of Geographical Systems* **4**(3) 251-274. doi: [10.1007/s101090200086](http://dx.doi.org/10.1007/s101090200086)

**O’Sullivan D**. 2001. Graph-cellular automata: a generalised discrete urban and regional model. *Environment and Planning B: Planning & Design* **28**(5) 687-705. doi: [10.1068/b2707](http://dx.doi.org/10.1068/b2707)

Haklay M, T Schelhorn, **D O’Sullivan** and M Thurstain-Goodwin. 2001. "So go down town": Simulating pedestrian movement in town centres. *Environment and Planning B: Planning & Design* **28**(3) 343-359. doi: [10.1068/b2758t](http://dx.doi.org/10.1068/b2758t)

Torrens PM and **D O’Sullivan**. 2001. Cellular automata and urban simulation: where do we go from here? *Environment and Planning B: Planning & Design* **28**(2) 163-168. doi: [10.1068/b2802ed](http://dx.doi.org/10.1068/b2802ed)

**O’Sullivan D** and A Turner. 2001. Visibility graphs and landscape visibility analysis. *International Journal of Geographical Information Science* **15**(3) 221-237. doi: [10.1080/13658810151072859](http://dx.doi.org/10.1080/13658810151072859)

Turner A, M Doxa, **D O’Sullivan** and A Penn. 2001. From isovists to visibility graphs: a methodology for the analysis of architectural space. *Environment and Planning B: Planning & Design* **28**(1) 103-121. doi: [10.1068/b2684](http://dx.doi.org/10.1068/b2684)

**O’Sullivan D**. 2001. Exploring spatial process dynamics using irregular cellular automaton models. *Geographical Analysis* **33**(1) 1-18. doi: [10.1111/j.1538-4632.2001.tb00433.x](http://dx.doi.org/10.1111/j.1538-4632.2001.tb00433.x)

**O’Sullivan D**. and M Haklay. 2000. Agent-based models and individualism: is the world agent-based? *Environment and Planning A* **32**(8) 1409-1425. doi: [10.1068%2Fa32140](http://doi.org/10.1068%2Fa32140)

**O’Sullivan D**, A Morrison and J Shearer. 2000. Using desktop GIS for the investigation of accessibility by public transport: an isochrone approach. *International Journal of Geographical Information Science* **14**(1) 85-104. doi: [10.1080/136588100240976](http://dx.doi.org/10.1080/136588100240976)

## book chapters
**D O’Sullivan**. 2018. Cartography and geographic information systems. In J Ash, R Kitchin and A Leszczynski (eds), *Digital Geographies*, (Los Angeles: Sage), pages 118-128.

**D O’Sullivan**. 2018. Big data ... why (oh why?) this computational social science? In JE Thatcher, J Eckert and A Shears (eds), *Thinking Big Data in Geography: New Regimes, New Research*, (Lincoln: University of Nebraska Press), pages 21-38. doi: [10.2307/j.ctt21h4z6m.7](http://dx.doi.org/10.2307/j.ctt21h4z6m.7)

LR Bergmann and **D O’Sullivan**. 2017. Computing with many spaces: Generalizing projections for the digital geohumanities and GIScience. In *Proceedings of GeoHumanities’17: 1st ACM SIGSPATIAL Workshop on Geospatial Humanities*, Redondo Beach, CA, November 7-10 (GeoHumanities’17), pages 31-38. doi: [10.1145/3149858.3149866](http://dx.doi.org/10.1145/3149858.3149866)

Thatcher JE, LR Bergmann and **D O’Sullivan**. 2016. Searching for common ground (again). In *Short Paper Proceedings of 9th International Conference on Geographical Information Science*, eds JA Miller, **D O’Sullivan** and N Wiegand, (Montreal, Canada), pages 304-307. doi: [10.21433/B3118nq409qz](http://dx.doi.org/10.21433/B3118nq409qz)

Pfeffer K, J Martinez, **D O’Sullivan** and D Scott. 2015. Geo-Technologies for Spatial Knowledge: Challenges for Inclusive and Sustainable Urban Development. In J Gupta, K Pfeffer, H Verrest and M Ros-Tonen (eds), *Geographies of Urban Governance* (Cham: Springer International Publishing), pages 147-173. doi: [10.1007/978-3-319-21272-2_8](http://dx.doi.org/10.1007/978-3-319-21272-2_8)

**O’Sullivan D**. 2014. Spatial Network Analysis. In Handbook of Regional Science (eds MM Fischer and P Nijkamp). Springer, pages 1253-1273. doi: [10.1007/978-3-642-23430-9_67](http://dx.doi.org/10.1007/978-3-642-23430-9_67)

**O’Sullivan D**, JDA Millington, GLW Perry and J Wainwright. 2012. Agent-Based Models – Because They’re Worth It? In AJ Heppenstall, AJ Crooks, LM See, and M Batty (eds), *Agent-Based Models of Geographical Systems* (Springer: Dordrecht, Netherlands), pages 109-123. doi: [10.1007/978-90-481-8927-4_6](http://dx.doi.org/10.1007/978-90-481-8927-4_6)

Heppenstall AJ, AJ Evans, MH Birkin, JR Macgill and **D O’Sullivan**. 2005. The Use of Hybrid Agent-Based Systems to Model Petrol Markets. In T Terano, H Kita, H Kaneda, K Arai and H Deguchi (eds), *Agent-Based Simulation: From Modelling Methodologies to Real-World Applications*, Springer Series on Agent-Based Social Systems, pages 154-162. doi: [10.1007/4-431-26925-8_17](http://dx.doi.org/10.1007/4-431-26925-8_17)

**O’Sullivan D**. 2004. Too much of the wrong kind of data: implications for the practice of micro-scale spatial modelling. In MF Goodchild and D Janelle (eds), *Spatially Integrated Social Science: Examples of Best Practice* (Oxford University Press: Oxford), pages 95-107.

**O’Sullivan D**, JR Macgill and C Yu. 2003. Agent-based residential segregation: a hierarchically structured spatial model. In C Macal, M North and D Sallach (eds), *Agent 2003: Challenges in Social Simulation*, pages 493-507 (Argonne National Laboratory: Chicago). [www.agent2004.anl.gov/Agent2003.pdf](http://www.agent2004.anl.gov/Agent2003.pdf)

**O’Sullivan D**. 2002. Understanding the difference that space can make: toward a geographical agent modeling environment. In C. Macal and D. Sallach (eds), *Agent 2002: Ecology, Exchange, and Evolution*, pages 13-25 (Argonne National Laboratory: Chicago). [www.agent2003.anl.gov/proceedings/2002.pdf](http://www.agent2003.anl.gov/proceedings/2002.pdf)

**O’Sullivan D** and PM Torrens. 2001. Cellular models of urban systems. In S Bandini and T Worsch (eds), *Theoretical and Practical Issues on Cellular Automata, Proceedings of the Fourth International Conference on Cellular Automata for Research and Industry (ACRI 2000)*, October 4–6, Karlsruhe, Germany (Springer-Verlag: London), pages 108-116.  [Also available as CASA Working Paper 22 at [www.casa.ucl.ac.uk/cellularmodels.pdf](http://www.casa.ucl.ac.uk/ cellularmodels.pdf)

## dissertations
PhD: **O’Sullivan D**. 2000. [Graph-based Cellular Automaton Models of Urban Spatial Processes](https://southosullivan.com/phd/phd.zip). University College London.

MSc: **O’Sullivan D**. 1997. [Using GIS to create public transport travel time isochrones for the Glasgow area](http://southosullivan.com/msc/mastersThesis.pdf). University of Glasgow.
