---
title: "Skills"
description: "Some things I am (reasonably) good at"
---

### Writing
I have written [3 books](books.html) and [numerous articles, reviews, and book chapters](publications.html).

### Presenting
I have taught for over 20 years and can put together a mean slide show (I like to think...). These days, I use web-compatible formats, primarily [revealjs](https://revealjs.com) or [quarto](https://quarto.org). See my list of [talks](talks.html), or even the slides from [a class](https://dosull.github.io/Geog315/schedule) for examples.

### Coding
I have been programming for as long a I can remember. The more or less full list of languages would be, with those I have taught in **bold**: (Apple) BASIC, PASCAL, Fortran, 6502 assembler (just a little), C/C++ (again, only a little), Java (my masters and Phd work), **NetLogo**, **Visual Basic** (yeuch), **Python**, **R**, and JavaScript (also HTML and CSS if you can call those programming languages). Like I say... I've been programming for a long time.

These days, I use python and R weekly. 

I am not a software developer, but if called on can write [well organised and documented code](https://dosull.github.io/weaving-space/doc/weavingspace/).

I love [NetLogo](https://ccl.northwestern.edu/netlogo/), but freely admit that it is a little... _niche_ (surprisingly powerful though, see [this geographical COVID model I built in lockdown](https://github.com/DOSull/spatial-epi)). 

I'm sure I have other languages in me: Julia and Rust seem particularly interesting, but I may wait for more mature geospatial stacks to emerge before engaging with them. I 

### Simulation modelling
See above re NetLogo. I've also written [a book about this](books.html#spatial-simulation-exploring-pattern-and-process).

### Web
Most of my web stuff is linked from these pages, so just have a look around. The most complicated web-thing I've built is probably [this New Zealand 2018 commute visualization](https://dosull.github.io/commute-viewer/commute-viewer-app/). I am certainly not a web developer, but am happy to roll up my sleeves and figure stuff out if called on!

### Project management
In most of my academic life I have been a team member rather than a team leader. Before academia I was a project engineer leading build, test, commissioning and maintenance of production line laser-scanning inspection equipment, working with major multinationals such as IBM, Kodak, Dow Chemical, and Sony. In that role I learned a great deal about project management and people management.
