---
title: "GeoCart'2024"
description: Reflections on the meeting
author: "David O'Sullivan"
categories:
  - cartography
  - spatial
  - aotearoa
  - 'time-space'
date: 08-30-2024
draft: true
---

Another (even-number year) August over and [another GeoCart' is over](https://cartography.org.nz/geocart2024).

As ever, this was a fun meeting. 

The passing last year of [Igor Drecki](https://natlib.govt.nz/blog/posts/remembering-igor-drecki-1966-2023) inevitably cast a shadow, but the organisers of GeoCart'2024 can be proud of what they achieved in putting on a meeting that Igor would have enjoyed. It bore all the hallmarks of Igor's vision for the meeting. Many keynotes (perhaps too many, but more on that below...) and many opportunities for informal discussion and exchange in the breaks between presentations, over lunch, and at the Icebreaker and Conference Dinner events. The latter in particular was really excellent&mdash;I don't recall ever before having FOUR choices of starter, main, and dessert at a catered sit-down meal like this one: well done [Dockside](https://dockside.co.nz/).^[Disclaimer: I have not been recompensed in any form by Dockside.] 

Given Wellington's current public sector uh... _situation_ attendance was as expected down a little, but there were still enough faces old and new for the meeting to retain its usual friendly buzz, without it being too overwhelming.

## Keynotes
So many keynotes... A two-and-a-half day meeting with six (yes SIX!) 'all-hands' presentations seems perhaps a little [too much of a good thing](#too-much-of-a-good-thing). Having said that, _all the keynotes were excellent_. Like, **really excellent**. I didn't necessarily agree with everything everyone said, but I was certainly engaged throughout. In chronological order

+ [**Ocean Mercier**](https://people.wgtn.ac.nz/ocean.mercier) kicked things off with 'Te Taunaha Whenua: Mapping Connections to Place' emphasising the role that maps and mapping play in defining and making place, and the more than coincidental relationship between those processes and colonisation and (yay!) decolonisation. I loved that Ocean shared her longtime love of orienteering&mdash;she was even heading off on a [rogaining](https://en.wikipedia.org/wiki/Rogaining) one evening of the conference so is still doing it.^[That word rogaining is very _weird_ derived from the given names of its 'inventors' ROd, GAil, and NEil. The names of new sports aren't what they used to be: see also pickleball.]
+ [**Daniel Huffman**](https://somethingaboutmaps.wordpress.com/) in their presentation 'Sharing the Emotional Work of Mapping' spoke to a topic that has been front of mind a lot for me in the last few months, namely the rollercoaster ride associated with the uncertainties of taking on projects as an when they arrive. Balancing ones ambitions for the creative work you do against the expectations of paying clients is an often unacknowledged aspect of the work many of us do. I have to confess to some disappointment that we didn't get some [Huffman eye candy](https://somethingaboutmaps.com/Client-Work) along the way, but instead had to content ourselves with [Madison, Wisconsin's&mdash;admittedly very smart&mdash;flag](https://en.wikipedia.org/wiki/Flag_of_Madison%2C_Wisconsin).
+ [**Daniel O'Donohue**](https://mapscaping.com/). After Daniel H's quietly reflective take on the emotional journey of mapping, next morning geospatial podcaster Daniel O, self-described [geospatial evangelist](), gave everyone a good kick in the pants and encouraged us all to get busy making millions on the interwebs. Some of this talk leaned a bit too much for cycnical old gen-X-er me into the social media influencer vibe, but more than a couple of people were taking notes and I expect to see mass-market cartography rocket to the top of Aoteroa's export earnings charts in the years to come. Seriously though, I did have a couple of conversations with folks prompted by Daniel O's talk to explore the possibilities for getting paid more for their world class skills. Being underappreciated and underpaid is a problem in cartography/geospatial^[This [recent episode of the MapScaping podcast](https://mapscaping.com/podcast/way-you-talk-about-your-geospatial-skills-is-costing-you-money/) is thought-provoking on the subject.] so I wish them all the best, and will join them, just as soon as I come up with an idea... Oh yes, also: we all got socks (I'm wearing mine now).
+ [**David Garcia**]()
+ [**Sarah Bell**]()
+ [**Wendy Shaw**]()

### Too much of a good thing?
So... I'll say it again: all the keynotes were excellent. I can't help wondering even so, if this balance in the the meeting speaks a bit too much to a lack of confidence in work going on here in Aoteroa New Zealand.

## Other highlights
With two tracks, you can't catch 'em all, so this is inevitably a partial perspective...



### Society business

## I am biased but...